# Generated by Django 3.2 on 2021-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_rename_room_id_reservationmodel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='reservationmodel',
            unique_together={('date', 'room_id')},
        ),
    ]
